### ISSUE TITLE
PtrHashTable issue with intel 19.1.0.166 20191121

### ISSUE THREAD

**Issue by jdhughes-usgs** [MODFLOW-USGS/modflow6#1954]
**Describe the bug**
Cannot build 6.6.0.dev0 with Intel 64 19.1.0.166 20191121. Issue with PtrHashTable. We need to build be able to build with Intel IFORT 19.1.0.166 20191121 to compile on USGS HPC. The error message is listed below.

```
FAILED: src/libmf6core.a.p/Utilities_PtrHashTable.f90.o src/libmf6core.a.p/ptrhashtablemodule.mod 
ftn -Isrc/libmf6core.a.p -Isrc -I../src -Isrc/libmf6_external.a.p -I/opt/cray/pe/petsc/3.14.5.0/real/INTEL/19.1/x86_skylake/include -I/opt/cray/pe/mpt/7.7.19/gni/mpich-intel/16.0/include -I/opt/cray/rca/2.2.20-7.0.3.0_24.22__g8e3fb5b.ari/include -I/opt/cray/pe/pmi/5.0.17/include -I/opt/cray/xpmem/default/include -I/opt/cray/gni-headers/default/include -I/opt/cray/ugni/default/include -I/opt/cray/udreg/default/include -I/opt/cray/alps/6.6.67-7.0.3.0_32.19__gb91cd181.ari/include -I/opt/cray/wlm_detect/1.3.3-7.0.3.0_49.6__g7109084.ari/include -I/opt/cray/krca/2.2.8-7.0.3.0_36.22__g59af36e.ari/include -I/opt/cray-hss-devel/9.0.0/include -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -stand=f08 -g -traceback -O2 -fpe0 -no-heap-arrays -traceback -diag-disable:7416 -diag-disable:7025 -diag-disable:5268 -D__WITH_PETSC__ -D__WITH_MPI__ -fPIC -module src/libmf6core.a.p -gen-dep=src/libmf6core.a.p/Utilities_PtrHashTable.f90.o -gen-depformat=make -o src/libmf6core.a.p/Utilities_PtrHashTable.f90.o -c ../src/Utilities/PtrHashTable.f90
../src/Utilities/PtrHashTable.f90(42): error #6053: Structure constructor may not have components with the PRIVATE attribute   [THIS]
    itr = PtrHashTableIteratorType(this%buckets)
-----------------------------------^
compilation aborted for ../src/Utilities/PtrHashTable.f90 (code 1)
```

slurm output file attached. [slurm-4909849.log](https://github.com/user-attachments/files/16253914/slurm-4909849.log) 

**To reproduce**
Build with intel 19.1.0.166 "ifort (IFORT) 19.1.0.166 20191121"

**Expected behavior**

**Screenshots**
None

**Environment**
 - Linux (SUSE Linux Enterprise Server 15 SP2)
 - 6.6.0.dev0
 - intel 19.1.0.166 "IFORT 19.1.0.166 20191121" Note: `ftn` is alias for ifort

**Comment by mjr-deltares** [comment]
@Manangka Should we discard this PR now?

**Comment by Manangka** [comment]
> @Manangka Should we discard this PR now?

Yes this has been resolved as part of #1956
